export const data = [
  { artist: "Nirvana", song: "Smells Like Teen Spirit" },
  { artist: "John Lennon", song: "Imagine" },
  { artist: "U2", song: "One" },
  { artist: "Michael Jackson", song: "Billie Jean" },
  { artist: "Queen", song: "Bohemian Rhapsody" },
  { artist: "The Beatles", song: "Hey Jude" },
  { artist: "Bob Dylan", song: "Like A Rolling Stone" },
  { artist: "Rolling Stones", song: "I Can't Get No Satisfaction" },
  { artist: "Sex Pistols", song: "God Save The Queen" },
  { artist: "Guns N' Roses", song: "Sweet Child O'Mine" },
  { artist: "The Clash", song: "London Calling" },
  { artist: "The Kinks", song: "Waterloo Sunset" },
  { artist: "The Eagles", song: "Hotel California" },
  { artist: "Elton John", song: "Your Song" },
  { artist: "Led Zeppelin", song: "Stairway To Heaven" },
  { artist: "Chubby Checker", song: "The Twist" },
  { artist: "Oasis", song: "Live Forever" },
  { artist: "Whitney Houston", song: "I Will Always Love You" },
  { artist: "David Bowie", song: "Life On Mars?" },
  { artist: "Elvis Presley", song: "Heartbreak Hotel" },
  { artist: "Judy Garland", song: "Over The Rainbow" },
  { artist: "Marvin Gaye", song: "What's Goin' On" },
  { artist: "Bruce Springsteen", song: "Born To Run" },
  { artist: "The Ronettes", song: "Be My Baby" },
  { artist: "Radiohead", song: "Creep" },
  { artist: "Simon & Garfunkel", song: "Bridge Over Troubled Water" },
  { artist: "Aretha Franklin", song: "Respect" },
  { artist: "Sly And The Family Stone", song: "Family Affair" },
  { artist: "ABBA", song: "Dancing Queen" },
  { artist: "The Beach Boys", song: "Good Vibrations" },
  { artist: "Jimi Hendrix", song: "Purple Haze" },
  { artist: "The Beatles", song: "Yesterday" },
  { artist: "Chuck Berry", song: "Jonny B Good" },
  { artist: "Bob Marley", song: "No Woman No Cry" },
  { artist: "Jeff Buckley", song: "Hallelujah" },
  { artist: "The Police", song: "Every Breath You Take" },
  { artist: "The Beatles", song: "A Day In The Life" },
  { artist: "Ben E King", song: "Stand By Me" },
  { artist: "James Brown", song: "Papa's Got A Brand New Bag" },
  { artist: "The Rolling Stones", song: "Gimme Shelter" },
  { artist: "Ray Charles", song: "What'd I Say" },
  { artist: "Dire Straits", song: "Sultans Of Swing" },
  { artist: "The Beach Boys", song: "God Only Knows" },
  { artist: "The Righteous Brothers", song: "You've Lost That Lovin' Feeling" },
  { artist: "The Who", song: "My Generation" },
  { artist: "Martha Reeves and the Vandellas", song: "Dancing In The Street" },
  { artist: "Prince", song: "When Doves Cry" },
  { artist: "Sam Cooke", song: "A Change Is Gonna Come" },
  { artist: "Ike and Tina Turner", song: "River Deep Mountain High" },
  { artist: "The Emotions", song: "Best Of My Love" },
];
